### ISSUE TITLE
Make sure all API methods accept `sample_domain` as `None`

### ISSUE THREAD

**Issue by kachayev** [scikit-adaptation/skada#17]
In this case the method has to derive domain labels using `y` masking. If masking is not done or, in a way, ambiguous, we should throw `ValueError` to report inconsistent inputs.

Typically done with `allow_auto_sample_domain=True` param for `check_*_domain` utils. I'm not sure this is implemented consistently throughout all methods. Also, test cases to cover this are absolutely necessary.

**Comment by YanisLalou** [comment]
By default `allow_auto_sample_domain` is set to false in the `check_X_y_domain` function. Doesn't it make more sense to set it to true by default?

**Comment by kachayev** [comment]
Yes, I agree that would be a more sensible default option.
