### ISSUE TITLE
Center data when using Coral

### ISSUE THREAD

**Issue by antoinecollas** [scikit-adaptation/skada#191]
Center data when using Coral algorithm.
See https://arxiv.org/pdf/1612.01939

**Comment by tgnassou** [comment]
When the reg parameter is set to "auto" is what `CoralAdapter` does no ?

**Comment by rflamary** [comment]
I dont' see anywhere in the CORAL code a centering step but I might have missed something

**Comment by antoinecollas** [comment]
#211 fixed it
