### ISSUE TITLE
Scikit-learn 1.5 breaks skada

### ISSUE THREAD

**Issue by antoinecollas** [scikit-adaptation/skada#207]
The latest release of Scikit-learn breaks skada. There are at least 2 problems:
- the `_approximate_mode` function is now in `sklearn.utils.extmath`. See: https://github.com/scikit-learn/scikit-learn/pull/28481
- the prototype of the method `_route_params` from the class `MethodMetadataRequest` changed. See: https://github.com/scikit-learn/scikit-learn/pull/28517

**Comment by kachayev** [comment]
The change mentioned here should not break the code as we are doing proper import from `sklearn.utils` 🤔

**Comment by kachayev** [comment]
Ah, okay. It's not exposed in the `__all__`... why would you ever change that
