### ISSUE TITLE
Cleanup `check_*_domain` utils

### ISSUE THREAD

**Issue by kachayev** [scikit-adaptation/skada#4]
The functions are already present in the code, so you can review them to understand their purposes. Given that they contain a significant number of internal clauses, it might be more straightforward to comprehend their functionality by reading the code directly.

*    check_X_y_domain [[link](https://github.com/scikit-adaptation/skada/blob/008306a918d5bd48ac670db1716b5c01dd024364/skada/_utils.py#L40C5-L40C21)]
*    check_X_domain [[link](https://github.com/scikit-adaptation/skada/blob/008306a918d5bd48ac670db1716b5c01dd024364/skada/_utils.py#L105)]

The overall purpose of these functions is similar to the check_array function in sklearn. Depending on the provided flags, they can execute a wide range of checks. In our case, it’s crucial to ensure that all the checks are: a) necessary, meaning they make sense and are utilized in the code; b) implemented correctly, which we can verify by creating test cases for each check; and c) properly documented in the docstrings, with sklearn serving as an excellent reference for how to structure these. Additionally, we need to relocate these functions to a publicly accessible utils.py module, as they are intended for both internal use and external use (by anyone developing their own estimators).

**Comment by YanisLalou** [comment]
PR #53
