### ISSUE TITLE
DA pipeline should fail if re-weighting adapter is used without estimator accepting weights

### ISSUE THREAD

**Issue by kachayev** [scikit-adaptation/skada#7]
Otherwise the adaptation doesn't really happen at all.

To make this happen, one needs to update the process of updating routing params within selectors so that if `AdaptationOutput` contains `sample_weight` key it asserts that the final estimator actually requested those. It might be tricky to do, and the check should likely happen at the final stage.

**Comment by antoinedemathelin** [comment]
Hi,
I may have a suggestion for the `sample_weight` request for the estimator with re-weighting method. We can use the `inspect` library to check if the `base_estimator` handles `sample_weight` or not, (in the `__init__` of the class, I think):

```python
fit_args = [p.name for p in inspect.signature(self.base_estimator.fit).parameters.values()]

if "sample_weight" in fit_args:
     self.estimator_use_sample_weight_ = True
else:
     self.estimator_use_sample_weight_ = False
```

If the `estimator` does not handle `sample_weight`, we can either raise an error or perform bootstrap, as done in AdaBoostRegressor, cf. [#L1149](https://github.com/scikit-learn/scikit-learn/blob/719c0c6036ac99d45ffb45ed7c8b4e4b221384b5/sklearn/ensemble/_weight_boosting.py#L1149), in which case, we may warn the user that bootstrap is performed ?

What do you think ?

**Comment by kachayev** [comment]
@antoinedemathelin I partially answered this in #89 

I think I will write a much longer explanation in Slack shortly, as I understand the confusion. The routing in sklearn does use `inspect` to compile a list of rules how objects should interact. We should not try to come up with own logic for this, it will make things harder. This is the [documentation](https://scikit-learn.org/stable/metadata_routing.html) from sklearn, it uses `sample_weight` almost exclusively to explain how different use cases should be handled by the user. And there are quite a few of them. The basic still boils down to

```python
lr = LogisticRegression().set_fit_request(sample_weight=True)
```

If we try to be smarter and guess up front what the user wants, we immediately bump into the fact that many (most?) estimators that work with weights could also work without them. Which mean that the function signature includes `sample_weight` parameter. In the pipeline there's no way to tell where weights given by the user should go. Maybe there's a transformer there which consumes those, and everything else works w/o weights. The flexibility of combining things together makes it hard, and fundamentally this was the reason to introduce routing mechanism in the first place.

**Comment by antoinedemathelin** [comment]
Thank you for the response,
Yes, I think, you have right, I didn't know this Metadata Routing API from sklearn... 

Bootstrapping can mislead the user in some cases, indeed... But for me, it is still annoying that I cannot use `sample_weight` with `KNeighborsClassifier` for instance, while it seems very straight-forward to handle...
